const { withNativeWind } = require("nativewind/metro");

// `input` must point to a CSS file inside the consumer app's project root
// (NativeWind v4 reads the tailwind config relative to it). The default
// "./global.css" matches the file generated by `fg-mobile-ui-init`, which in
// turn does `@import "@fg-design-system/mobile-ui/global.css"`.
function withFGDesignSystem(config, options = {}) {
  const { input = "./global.css", ...rest } = options;
  return withNativeWind(config, { input, ...rest });
}

module.exports = { withFGDesignSystem };
